#!/bin/bash -x
   
   #restrict the alphabets and special charecters
   echo "enter the pattern"
   read pattern
   pinpat="^[0-9]{6}$"
   if [[ $pattern =~ $pinpat ]]
   then
   echo "valid"
   else
   echo "invalid"
   fi
